version: '2'

services:
  web:
    build:
      context: ./docker-env/5.6
      dockerfile: Dockerfile
    image: web-acme
    environment:
      - SERVERNAME=local.acme.co
      - SERVERALIAS=acme.local *.acme.local
      - DOCUMENTROOT=repo
      - DBNAME=acme
      - DBUSER=acme
      - DBPASS=acme
      - DBHOST=mysql
      - HOST_UID=1000
    volumes:
#     - ../envshare/:/envshare/
      - ./site/:/var/www/html/
#     - /home/docker/.ssh/:/var/www/.ssh/
    links:
      - mysql
    labels:
      - 'traefik.backend=acme_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:local.acme.co'

  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=acme
      - MYSQL_USER=acme
      - MYSQL_PASSWORD=acme
    volumes:
      - db:/var/lib/mysql
      - ./etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  db:
