# Allow executing helper scripts and phpcs easily
export PATH="$PATH:/mnt/etc/scripts:$HOME/.composer/vendor/bin"
alias ll='ls -al'

alias drupalcs="phpcs --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,js,css,info,txt'"
alias drupalbp="phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md"
